# Generated by Django 3.1.5 on 2021-01-25 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category_name',
        ),
        migrations.AddField(
            model_name='blog',
            name='category_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blogs.category'),
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tags_names',
        ),
        migrations.AddField(
            model_name='blog',
            name='tags_names',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blogs.tag'),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='blog',
        ),
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blogs.blog'),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blogs.user'),
        ),
        migrations.RemoveField(
            model_name='content',
            name='blog',
        ),
        migrations.AddField(
            model_name='content',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blogs.blog'),
        ),
        migrations.RemoveField(
            model_name='content',
            name='category',
        ),
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blogs.category'),
        ),
        migrations.RemoveField(
            model_name='content',
            name='comment',
        ),
        migrations.AddField(
            model_name='content',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blogs.comment'),
        ),
        migrations.RemoveField(
            model_name='content',
            name='tag',
        ),
        migrations.AddField(
            model_name='content',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blogs.tag'),
        ),
        migrations.RemoveField(
            model_name='content',
            name='user',
        ),
        migrations.AddField(
            model_name='content',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blogs.user'),
        ),
    ]
