# Generated by Django 3.1.5 on 2021-01-26 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20210125_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token', models.CharField(max_length=120, verbose_name='Toekn')),
                ('date_creation', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Creation')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
