# Generated by Django 3.1.5 on 2021-01-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='token',
            name='password',
            field=models.CharField(max_length=50, null=True, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=120, verbose_name='Token'),
        ),
    ]
